// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP4ObZ6kDjT-rO2qiCVtAw50bHA21cea0',
    appId: '1:566601646538:web:7650020575d86290d34f33',
    messagingSenderId: '566601646538',
    projectId: 'uniquesofindia-c4f7b',
    authDomain: 'uniquesofindia-c4f7b.firebaseapp.com',
    storageBucket: 'uniquesofindia-c4f7b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJAkZzwKEJbTNy1ThR_aZ4TCq5OHm_j4g',
    appId: '1:566601646538:android:7cd691c11c715905d34f33',
    messagingSenderId: '566601646538',
    projectId: 'uniquesofindia-c4f7b',
    storageBucket: 'uniquesofindia-c4f7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD87XXZQJvPDVY2xdHWHRggiBC2qGmg0O4',
    appId: '1:566601646538:ios:1bd40fe139826df2d34f33',
    messagingSenderId: '566601646538',
    projectId: 'uniquesofindia-c4f7b',
    storageBucket: 'uniquesofindia-c4f7b.appspot.com',
    androidClientId: '566601646538-qtlovdf4dsmlbm1t0upr49nbgdtp8kg3.apps.googleusercontent.com',
    iosClientId: '566601646538-ahu9f3di16dhievj2o6i6hv32l3oc757.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD87XXZQJvPDVY2xdHWHRggiBC2qGmg0O4',
    appId: '1:566601646538:ios:1bd40fe139826df2d34f33',
    messagingSenderId: '566601646538',
    projectId: 'uniquesofindia-c4f7b',
    storageBucket: 'uniquesofindia-c4f7b.appspot.com',
    androidClientId: '566601646538-qtlovdf4dsmlbm1t0upr49nbgdtp8kg3.apps.googleusercontent.com',
    iosClientId: '566601646538-ahu9f3di16dhievj2o6i6hv32l3oc757.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoapp',
  );
}
