// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Ih2tE5knxjMwpCNcNzxeXTYIPTNUgp8',
    appId: '1:976258601942:web:7ca165c8372efe7dc20a77',
    messagingSenderId: '976258601942',
    projectId: 'first-app-48a0e',
    authDomain: 'first-app-48a0e.firebaseapp.com',
    storageBucket: 'first-app-48a0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX4HU72WmTT3NtIrvgtj6hZQDqmufMArg',
    appId: '1:976258601942:android:e07c5722157396a8c20a77',
    messagingSenderId: '976258601942',
    projectId: 'first-app-48a0e',
    storageBucket: 'first-app-48a0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEVbyRkc99lY5QrxQXJGTUGLKiwXRrAQM',
    appId: '1:976258601942:ios:e16f698239ea8658c20a77',
    messagingSenderId: '976258601942',
    projectId: 'first-app-48a0e',
    storageBucket: 'first-app-48a0e.appspot.com',
    iosClientId: '976258601942-d1ht5377538hm8v54v9q3oi9ljuvpvvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEVbyRkc99lY5QrxQXJGTUGLKiwXRrAQM',
    appId: '1:976258601942:ios:e16f698239ea8658c20a77',
    messagingSenderId: '976258601942',
    projectId: 'first-app-48a0e',
    storageBucket: 'first-app-48a0e.appspot.com',
    iosClientId: '976258601942-d1ht5377538hm8v54v9q3oi9ljuvpvvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoapp',
  );
}
